### ISSUE TITLE
Handle 11001 Errors

### ISSUE THREAD

**Issue by kevinswarner** [MattouFP/mongoose-beautiful-unique-validation#1]
I did not see that this plugin handles 11001 errors from Mongo, which occur when violating a unique index constraint when saving an existing document. Is this something that was left out for a specific reason? I was thinking about using this plugin, but was not sure why this was left out. I could add this, but wanted to check first.

**Comment by MattouFP** [comment]
There is no specific reason for leaving out 11001 errors, thanks for pointing that out!
Do you want to implement that, or should I do it?

**Comment by kevinswarner** [comment]
I will do some further testing to be sure and if it is missing, I will take a stab at adding it. Thanks!

**Comment by MattouFP** [comment]
Merged, thanks!
